var annotated_dup =
[
    [ "fake_mbed", "namespacefake__mbed.html", "namespacefake__mbed" ],
    [ "Geometry2d", null, [
      [ "Arc", "class_geometry2d_1_1_arc.html", "class_geometry2d_1_1_arc" ],
      [ "Circle", "class_geometry2d_1_1_circle.html", "class_geometry2d_1_1_circle" ],
      [ "CompositeShape", "class_geometry2d_1_1_composite_shape.html", "class_geometry2d_1_1_composite_shape" ],
      [ "Line", "class_geometry2d_1_1_line.html", "class_geometry2d_1_1_line" ],
      [ "Point", "class_geometry2d_1_1_point.html", "class_geometry2d_1_1_point" ],
      [ "Polygon", "class_geometry2d_1_1_polygon.html", "class_geometry2d_1_1_polygon" ],
      [ "Rect", "class_geometry2d_1_1_rect.html", "class_geometry2d_1_1_rect" ],
      [ "Segment", "class_geometry2d_1_1_segment.html", "class_geometry2d_1_1_segment" ],
      [ "Shape", "class_geometry2d_1_1_shape.html", "class_geometry2d_1_1_shape" ],
      [ "ShapeSet", "class_geometry2d_1_1_shape_set.html", "class_geometry2d_1_1_shape_set" ],
      [ "TransformMatrix", "class_geometry2d_1_1_transform_matrix.html", "class_geometry2d_1_1_transform_matrix" ]
    ] ],
    [ "mbed", null, [
      [ "I2CDriver", "classmbed_1_1_i2_c_driver.html", "classmbed_1_1_i2_c_driver" ],
      [ "I2CMasterRtos", "classmbed_1_1_i2_c_master_rtos.html", "classmbed_1_1_i2_c_master_rtos" ],
      [ "I2CSlaveRtos", "classmbed_1_1_i2_c_slave_rtos.html", "classmbed_1_1_i2_c_slave_rtos" ]
    ] ],
    [ "rtp", null, [
      [ "ControlMessage", "structrtp_1_1_control_message.html", "structrtp_1_1_control_message" ],
      [ "header_data", "structrtp_1_1header__data.html", "structrtp_1_1header__data" ],
      [ "packet", "classrtp_1_1packet.html", "classrtp_1_1packet" ],
      [ "RobotStatusMessage", "structrtp_1_1_robot_status_message.html", "structrtp_1_1_robot_status_message" ]
    ] ],
    [ "agc_cfg_struct", "structagc__cfg__struct.html", "structagc__cfg__struct" ],
    [ "AutoName", "class_auto_name.html", "class_auto_name" ],
    [ "AVR910", "class_a_v_r910.html", "class_a_v_r910" ],
    [ "BallSense", "class_ball_sense.html", "class_ball_sense" ],
    [ "Buzzer", "class_buzzer.html", "class_buzzer" ],
    [ "CC1201", "class_c_c1201.html", "class_c_c1201" ],
    [ "command_t", "structcommand__t.html", "structcommand__t" ],
    [ "CommLink", "class_comm_link.html", "class_comm_link" ],
    [ "CommModule", "class_comm_module.html", "class_comm_module" ],
    [ "CommPort", "class_comm_port.html", "class_comm_port" ],
    [ "Console", "class_console.html", "class_console" ],
    [ "Decawave", "class_decawave.html", "class_decawave" ],
    [ "DS2411_t", "struct_d_s2411__t.html", "struct_d_s2411__t" ],
    [ "dw1000_api", "classdw1000__api.html", "classdw1000__api" ],
    [ "dwt_cb_data_t", "structdwt__cb__data__t.html", "structdwt__cb__data__t" ],
    [ "dwt_config_t", "structdwt__config__t.html", "structdwt__config__t" ],
    [ "dwt_deviceentcnts_t", "structdwt__deviceentcnts__t.html", "structdwt__deviceentcnts__t" ],
    [ "dwt_rxdiag_t", "structdwt__rxdiag__t.html", "structdwt__rxdiag__t" ],
    [ "dwt_txconfig_t", "structdwt__txconfig__t.html", "structdwt__txconfig__t" ],
    [ "ExceptionIterator", "class_exception_iterator.html", "class_exception_iterator" ],
    [ "Field_Dimensions", "struct_field___dimensions.html", "struct_field___dimensions" ],
    [ "FIRFilter", "class_f_i_r_filter.html", "class_f_i_r_filter" ],
    [ "FlashingTimeoutLED", "class_flashing_timeout_l_e_d.html", "class_flashing_timeout_l_e_d" ],
    [ "FPGA", "class_f_p_g_a.html", "class_f_p_g_a" ],
    [ "HackedKickerBoard", "class_hacked_kicker_board.html", "class_hacked_kicker_board" ],
    [ "IOExpanderDigitalInOut", "class_i_o_expander_digital_in_out.html", "class_i_o_expander_digital_in_out" ],
    [ "KickerBoard", "class_kicker_board.html", "class_kicker_board" ],
    [ "LogHelper", "class_log_helper.html", "class_log_helper" ],
    [ "MailHelper", "class_mail_helper.html", "class_mail_helper" ],
    [ "MCP23017", "class_m_c_p23017.html", "class_m_c_p23017" ],
    [ "motor_t", "structmotor__t.html", "structmotor__t" ],
    [ "motorErr_t", "structmotor_err__t.html", "structmotor_err__t" ],
    [ "MPU6050", "class_m_p_u6050.html", "class_m_p_u6050" ],
    [ "NeoColor", "struct_neo_color.html", "struct_neo_color" ],
    [ "NeoStrip", "class_neo_strip.html", "class_neo_strip" ],
    [ "Pid", "class_pid.html", "class_pid" ],
    [ "PidMotionController", "class_pid_motion_controller.html", "class_pid_motion_controller" ],
    [ "RadioProtocol", "class_radio_protocol.html", "class_radio_protocol" ],
    [ "registerSetting_t", "structregister_setting__t.html", "structregister_setting__t" ],
    [ "RobotModel", "class_robot_model.html", "class_robot_model" ],
    [ "RotarySelector", "class_rotary_selector.html", "class_rotary_selector" ],
    [ "RtosTimerHelper", "class_rtos_timer_helper.html", "class_rtos_timer_helper" ],
    [ "SharedSPI", "class_shared_s_p_i.html", "class_shared_s_p_i" ],
    [ "SharedSPIDevice", "class_shared_s_p_i_device.html", "class_shared_s_p_i_device" ],
    [ "SoftwareSPI", "class_software_s_p_i.html", "class_software_s_p_i" ],
    [ "StrobingTimeoutLEDs", "class_strobing_timeout_l_e_ds.html", "class_strobing_timeout_l_e_ds" ],
    [ "TimeoutLED", "class_timeout_l_e_d.html", "class_timeout_l_e_d" ],
    [ "Watchdog", "class_watchdog.html", null ]
];